apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: sealed-secrets
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj/sync-wave: "-1"
spec:
  project: default
  source: 
    repoURL: oci://ghcr.io/bitnami-labs/charts/sealed-secrets 
    chart: sealed-secrets
    targetRevision: 2.16.1
    helm:
      releaseName: sealed-secrets
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true 
